---
title: "20200204_COPD Sentiment Analysis"
author: "Emma"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(knitr)
library(kableExtra)
library(lubridate)
library(tableone)
library(forcats)
library(stringr)
library(janitor)
library(dplyr)
library(qwraps2)
library(plyr)
library(ggridges)
library(viridis)
library(RColorBrewer)
library(cowplot)
library(gridExtra)
library(beeswarm)
library(ggbeeswarm)
options(qwraps2_markup = "markdown")
```

# Create the dataset
```{r dataset_compilation, comment=FALSE }

# Read in dataset containing gold standard coding of responses to open-ended questions
  data <- read_csv(here::here("data", "20200205_Complete COPD Qualanalysis data_v2.csv"))

# Read in full dataset including responses from people who did not comment
  data_all<-read_csv(here::here("data", "20200211_COPD_Qual all data.csv"))


# Only keeping the unique identifier and the columns from data which contain the Gold Standard (i.e. human) coding of the comments
  data <- data %>%
  select(uid, comment_cat, sentim_1, sentim_2)


# Join them
  data <-merge(data_all, data, by="uid", all.x = TRUE)
  rm(data_all)
  
# Change colname of scr_6 to "vent" and scr_7 to "relat"
  data<-dplyr::rename(data, vent=scr_6, relat=scr_7)
```


#  Export to csv
```{r export}
write_csv(data, here::here("data", "20200217_COPD Qualanalysis data.csv"))
```

